# Generated by Django 5.1.3 on 2024-12-13 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_personallist_delete_listapersonal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personallist',
            name='movie_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='streaming.movie'),
        ),
        migrations.AlterField(
            model_name='personallist',
            name='tvshow_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='streaming.tvshow'),
        ),
    ]
