# Generated by Django 5.1.3 on 2024-12-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_alter_personallist_movie_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personallist',
            name='movie_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personallist',
            name='tvshow_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
